fix: ic_contact.xml crash - wrong XML namespace
Error: <vector> tag requires viewportWidth > 0
Cause: xmlns:android='http://android.com/apk/res/android' (missing 'schemas.')
Fix:   xmlns:android='http://schemas.android.com/apk/res/android'

This made Android unable to parse viewportWidth/viewportHeight attributes,
causing a crash every time ChatActivity tried to inflate chat.xml layout.